extract data from csv
iterate through each line
transform
    -remove cc data
    -remove name 
    -split up basket into name,size,price: float
    -convert date time to epoch 
- load into db
    - Create tables
     -prod
      -id (uuidv4): VARCHAR(36)
      -size: varchar(100)
      -name: varchar(100)
      -price: Decimal(15,2)
     -location
      -id
      -name: varchar(100)

     -orders
      -id: int AUTO_INC
      -date_time: int
      -transac_id: FK (transaction_id)
      -product_id: FK (product.id)
      -amount: DECIMAL(15,2)

     -transactions
      -id (uuidv4): VARCHAR(36)
      -date_time: int
      -location_id: FK (location.id)
      -payment_type: varchar(4)
      -total_amount: decimal(15,2)
- iterate through each transformed element
 - Load location 
  - get location_ name from transformed_row[1]
  -check if location_name is already in the DB
   - get the ID
  -else:
      -create and remember the ID
 - load product 
  -iterate through products from transformed_row
  - load product
   -if product already in db, query on (size, name, price)
    -get the ID
   -else 
    - insert into DB, remember the ID
 - load transaction 
  -create ID and remember
  - insert into DB: ID, Location_ID...
 - Load orders
  -no uuidv4
  -for each remembered product id
   -insert into DB: product_id, transaction_id...     